INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Trendforce',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),10,'Y',N'시장 분석 정보 제공.
(검색 시 키워드 : Display, Panel, TV, MNT, NBPC, SP, LED)','www.trendforce.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'NPD',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),20,'Y',N'시장 분석 정보 제공.
(검색 시 키워드 : SP, Auto, China, Panel, Display)','www.npd.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Sigmaintell',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),30,'Y',N'시장 분석 정보 제공.
(검색 시 키워드 : SP, Auto, China, Panel, Display)','www.sigmaintell.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'부분유료',N'중문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Global market insights',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),40,'Y',N'전자 제품에 대한 시장 분석 정보 제공.
(검색 시 키워드 : TV, MNT, NBPC, SP, Display, Industry)','www.gminsights.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'OECD',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),50,'Y',N'경제협력개발기구 홈페이지로, 국제/국가별 경제, 뉴스, 데이터, 교육 등 다양한 분야에 대한 자료 제공.','www.oecd.org',N'산업/시장동향/트렌드 (Trend)',N'기관/협회',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Research and Markets',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),60,'Y',N'lobal Research 회사로 IT, 서비스, 전자, 산업기계, 화학, 자동차, 의료, 바이오, 에너지 등 정보 제공.','www.researchandmarkets.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Market Research Future',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),70,'Y',N'Global Research 회사로 IT, 서비스, 전자, 산업기계, 화학, 자동차, 의료, 바이오, 에너지 등 정보 제공.','www.marketresearchfuture.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Markets and Markets',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),80,'Y',N'산업시장 동향분석 관련 정보제공.','www.marketsandmarkets.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'서울신문',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),90,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.seoul.co.kr',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'koreaherald - 코리아 헤럴드',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),100,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.koreaherald.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'MT - 머니투데이',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),110,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.mt.co.kr',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Hankookilbo - 한국일보',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),120,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.hankookilbo.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Sedaily - 서울경제',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),130,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.sedaily.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'hankyung - 한국경제',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),140,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.hankyung.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'파이낸셜 뉴스',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),150,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.fnnews.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'MBN - 매일경제',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),160,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.mk.co.kr',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'munhwa - 문화일보',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),170,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.munhwa.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'JoongAng Ilbo - 중앙일보',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),180,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','joongang.joins.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'HERALD - 헤럴드 경제',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),190,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','biz.heraldcorp.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'TheKoreaTimes - 코리아 타임스',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),200,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.koreatimes.co.kr',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'경향신문',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),210,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.khan.co.kr',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'DIGITALTIMES - 디지털 타임스',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),220,'Y',N'국내 신문기사
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.dt.co.kr',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'OLED info',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),230,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.oled-info.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Chicago Tribune - 시카고 트리뷴',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),240,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.chicagotribune.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Degital Trends - 디지털트랜드',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),250,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.digitaltrends.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Nikkei Asian - 닛케이 아시안',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),260,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','https://asia.nikkei.com/',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Expert Reviews - 엑스퍼트 리뷰',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),270,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.expertreviews.co.uk',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Forbes - 포브즈',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),280,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.forbes.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'What Hi-Fi - 왓 하이 파이',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),290,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.whathifi.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Phone Mantra-폰 만트라',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),300,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.phonemantra.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Tom''s Guide - 톰스가이드',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),310,'Y',N'해외 신문기사 및 팟캐스트
: 전자제품 회사 및 전자제품과 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.tomsguide.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'ZDNet - 지디넷코리아',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),320,'Y',N'전자, 정보통신, 최신 IT 트렌드, 비지니스 기술 정보 등 전자 업계 전반의 기사 제공.','http://www.zdnet.co.kr',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'DSCC',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),330,'Y',N'전자 제품에 대한 시장 분석 정보제공.
(검색 시 키워드 : TV, MNT, NBPC, SP, Display, Industry)','www.displaysupplychain.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'TRENDBIRD-트렌드 버드',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),340,'Y',N'Global 시장 및 기술, 산업에 대한 트렌드 분석 정보제공.(검색 시 키워드 : Trend, Industry)','http://www.trendbird.biz',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Gfk',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),350,'Y',N'전 세계 소비자 제품 및 소매 업계를 위한 세계 최고의 AI 기반 데이터 정보제공.','www.gfk.com',N'산업/시장동향/트렌드 (Trend)',N'분석/조사업체',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Display Daily - 디스플레이 데일리',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),360,'Y',N'해외 신문기사 및 팟캐스트. 전자제품 회사 및 전자제품 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공.
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.displaydaily.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'부분유료',N'영문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'통계청',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),370,'Y',N'국내/국제 통계 데이터 제공을 통해 산업 / 마켓 / 트렌드 정보 제공.','www.kostat.go.kr',N'산업/시장동향/트렌드 (Trend)',N'기관/협회',N'무료',N'국문','-1', Getdate());
INSERT INTO VCP_CUSTOM01.DBO.TBP_EXTERNAL_URL_MASTER (CompanyCode, MasterName, ParentCode, SortOrder, UseYN, Description, SiteUrl, CategoryName, MainAgentName, ChargeName, LanguageName, CreateUserID, CreateDate) VALUES (N'LG 디스플레이',N'Tech Radar - 테크 레이더',(SELECT Code FROM VCP_CUSTOM01.dbo.TBP_EXTERNAL_URL_MASTER WHERE CompanyCode=N'LG 디스플레이' AND ParentCode=0),380,'Y',N'해외 신문기사 및 팟캐스트. PC, TVs, Mobile, Phone, Laptops, Cameras 등 IT 제품 전문 리뷰, 전자제품 회사 및 전자제품 관련 기술 등 산업 트렌드에 대한 각종 뉴스 정보 제공.
(검색시 키워드 : TV, MNT, NBPC, Tablet, SP, Display, Panel, LCD, OLED, LGD, SDC)','www.techradar.com',N'산업/시장동향/트렌드 (Trend)',N'신문/언론/잡지사',N'무료',N'영문','-1', Getdate());