-- VCP_CUSTOM01.dbo.TBP_DELIVERABLE_BOOKMARKS definition

-- Drop table

-- DROP TABLE VCP_CUSTOM01.dbo.TBP_DELIVERABLE_BOOKMARKS;

CREATE TABLE VCP_CUSTOM01.dbo.TBP_DELIVERABLE_BOOKMARKS (
	BookmarkID int IDENTITY(1,1) NOT NULL,
	DeliverableID int NOT NULL,
	UserID int NOT NULL,
	CONSTRAINT PK_TBP_DELIVERABLE_BOOKMARKS PRIMARY KEY (BookmarkID),
	CONSTRAINT UK_TBP_DELIVERABLE_BOOKMARKS UNIQUE (DeliverableID,UserID)
);